CREATE OR REPLACE PROCEDURE insert_sales_cur( s_date date)
AS
CURSOR sale_cursor
IS
SELECT SALES_DATE, ORDER_ID, PRODUCT_ID, CUSTOMER_ID
FROM sales
WHERE SALES_DATE = S_DATE;

TYPE l_salestable IS TABLE OF sales%ROWTYPE;
l_sales l_salestable;

BEGIN
	OPEN sale_cursor;
	LOOP
		FETCH sale_cursor BULK COLLECT INTO l_sales
		LIMIT 100;
		
		FORALL INDX in 1 .. l_sales.count SAVE EXECEPTIONS --save
		INSERT INTO sales_2 VALUES l_sales(indx);
		
		EXIT WHEN sale_cursor%NOTFOUND;
	END LOOP;
	CLOSE sale_cursor;

EXCEPTION
	WHEN OTHERS
	THEN
		IF SQLCODE = -24381 
		THEN
			FOR INDX in 1 .. SQL%BULK_EXECPTIONS.COUNT
			LOOP
				DBMS_OUTPUT.PUT_LINE(SQL%BULK_EXCEPTIONS(INDX).ERROR_INDEX);
				DBMS_OUTPUT.PUT_LINE(SQLERRM(-SQL%BULK_EXCEPTIONS (INDX).ERROR_CODE));
			END LOOP;
		ELSE RAISE;
		END IF;
END;
/
