CREATE SEQUENCE SQSTARTER NOCYCLE INCREMENT BY 5;
INSERT INTO HBO (COL1, COL2) VALUES (SQSTARTER.NEXTVAL, 'HB1');
COMMIT;
SELECT * FROM HBO;
DESC HBO;

SELECT SQSTARTER.CURRVAL FROM DUAL;

SELECT '15-DEC-07', ROUND(TO_DATE('20-DEC-07'), 'MM') AS "ROUNDBYMO", TRUNC(TO_DATE('20-DEC-07'), 'MM') AS "TRUNCBYMO" FROM DUAL;

SELECT NUMTOYMINTERVAL(18.5, 'YEAR') FROM DUAL;
SELECT NUMTODSINTERVAL(37.5, 'HOUR') FROM DUAL;

SELECT TO_NUMBER('$900,000', '$9,999,999.99') FROM DUAL;
SELECT TO_CHAR(9000000, '$9,999,999.99') FROM DUAL;

SELECT TO_CHAR(TO_DATE('25-DEC-50', 'DD-MON-YY'), 'YYYY') as "YYYY", TO_CHAR(TO_DATE('25-DEC-50', 'DD-MON-RR'), 'RRRR') as "RRRR"  FROM DUAL;
SELECT TO_CHAR(TO_DATE('25-DEC-99'), '"THE DAY WAS:"FM ddth "of" MONTH, YYYY') FROM DUAL;
SELECT TO_TIMESTAMP(SYSDATE, 'RRRR-MON-DD HH24:MI:SS:FF') as "TIMESTAMP", TO_TIMESTAMP_TZ(SYSDATE, 'RRRR-MON-DD HH24:MI:SS') as "TIMESTAMP_TZ" FROM DUAL;
SELECT TO_YMINTERVAL('3-5') FROM DUAL;

SELECT SYSDATE FROM DUAL;
SELECT * FROM THENUMBERS;

SELECT * FROM THENUMBERS WHERE (NUM_, NAME_) = (SELECT DISTINCT NUM_, NAME_ FROM THENUMBERS WHERE NUM_ = 10 AND NAME_ = 'PETER');
