CREATE TABLE TIMEMACHINE ( C_DATE DATE, C_TS TIMESTAMP, C_TSWTZ TIMESTAMP WITH TIME ZONE, C_TSWLTZ TIMESTAMP WITH LOCAL TIME ZONE );

INSERT INTO TIMEMACHINE VALUES (SYSDATE, SYSDATE, SYSDATE, SYSDATE);
COMMIT;

SELECT * FROM TIMEMACHINE;

CREATE TABLE TIMEMACHINE2 ( iy2m INTERVAL YEAR to MONTH, id2s INTERVAL DAY TO SECOND);

INSERT INTO TIMEMACHINE2 VALUES ('4 5:00:30.000', NULL);
DROP TABLE TIMEMACHINE2;

SELECT INTERVAL '4-2' YEAR to MONTH FROM DUAL;
SELECT INTERVAL '4 5:30:00' DAY to SECOND FROM DUAL;